DECLARE
    myclob CLOB;
BEGIN
    myclob := '';
    
    myclob := myclob || '<p>This plugin takes a CLOB and outputs it to the Apex page.</p>
    <p>CLOBs are a nuisance in Apex, since it''s can''t really handle anything over 32 KB natively. Most likely, this would be some complicated bit of HTML that the out-of-the box Apex item types can''t handle, or some formatted HTML you already have in a database.</p>
    <p><b>Instructions:</b></p>
    <ol>
    <li>Create a "Plug-ins" type region and select "CLOB Region" as the plugin type.</li>
    <li>Continue creating your region as normal. In the Display Attributes section, if you select a region template of "No Template" (or similar, depending on your Apex theme), the region will not get borders or a title.</li>
    <li>For the Source section, the easiest way is to specify a SQL query that selects your CLOB. It should return exactly one row and one column. An Apex collection works very well here.</li>
    <li>It''s likely that your CLOB contains HTML characters, in which case, edit your region and change "Escape Special Characters" to "No". <em>It is your responsibility to make sure all HTML entities like "&amp;" are properly escaped.</em>
    </ol>
    <p>These instructions are a CLOB. Here is about 40 KB of additional text:</p>';
    
    myclob := myclob || '<p class="lorem">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget augue vitae turpis convallis sagittis. Nam ex massa, ultricies eget porttitor id, gravida non libero. Fusce vehicula nisi ut lorem pulvinar, ornare iaculis sem faucibus. Aliquam quis nisl nulla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst. Aenean vel cursus dolor. Nam blandit magna non nibh molestie vulputate. Sed eget pulvinar arcu.</p>';
    myclob := myclob || '<p class="lorem">Aliquam volutpat est tincidunt, egestas leo id, lacinia lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sollicitudin venenatis eros id porta. Ut faucibus dui vel malesuada viverra. In cursus, nibh vitae sodales pretium, quam libero gravida erat, in accumsan purus leo quis nisi. Maecenas fermentum leo eu sagittis elementum. Vivamus cursus leo eu placerat porta. Vivamus aliquet nulla elit, vitae semper erat lobortis ultricies. Nullam felis nisi, tincidunt vel orci vitae, porttitor luctus turpis. Mauris dignissim diam vel sem dignissim, at euismod lacus sodales. Praesent molestie velit at ipsum elementum rhoncus. Fusce neque diam, eleifend at aliquet ac, pulvinar in orci. Aenean feugiat magna sed lacus ullamcorper, nec porttitor turpis bibendum. Vivamus et suscipit ex. Phasellus egestas dictum diam. Nulla tincidunt tortor nec facilisis pretium.</p>';
    myclob := myclob || '<p class="lorem">Praesent dignissim odio lacinia, suscipit ex sed, laoreet elit. Mauris at odio sit amet erat finibus mollis. Aenean id fermentum ante. Etiam sed aliquam enim. Fusce dictum arcu ut mi gravida tincidunt vitae ut ipsum. Aenean non elit at diam consectetur imperdiet at tristique dolor. Quisque nec rhoncus est, vitae dignissim dolor. Nulla turpis sem, ultrices in rhoncus sed, iaculis vitae lorem. Phasellus fermentum laoreet tempor. Aliquam dictum nibh a scelerisque ultricies. Mauris ornare, augue vitae sollicitudin auctor, ipsum est egestas tortor, et hendrerit eros diam et quam. Suspendisse in elit ac velit tincidunt mattis. Ut vitae imperdiet sapien.</p>';
    myclob := myclob || '<p class="lorem">Cras nec tellus rhoncus, ornare augue sed, aliquam ligula. Maecenas mollis sapien ut tellus blandit aliquam. Curabitur vehicula quam libero, sed imperdiet massa porttitor nec. Vivamus posuere eros dictum, maximus ex sit amet, tempor sapien. Maecenas pulvinar quam eget massa ullamcorper fringilla. Duis nec finibus metus, et pulvinar magna. Integer ornare risus vel leo dignissim, id tristique urna placerat. Aenean malesuada tincidunt eros, non interdum velit faucibus vel. Curabitur et orci sodales, mollis justo non, elementum justo. Maecenas vulputate orci lectus, nec scelerisque ipsum cursus in.</p>';
    myclob := myclob || '<p class="lorem">Pellentesque justo sem, finibus vitae aliquam quis, malesuada in tortor. Vestibulum id diam enim. Suspendisse potenti. Vivamus porttitor lacus sed tempus porta. Sed odio lacus, convallis eget nulla eget, eleifend porta leo. Cras gravida velit quis turpis venenatis pellentesque. Aliquam dui dui, placerat in tortor non, vehicula mollis lectus. Vivamus sit amet libero lectus. Donec metus nibh, faucibus eget congue sit amet, tempor at elit. Donec eget massa vitae nisi posuere ultricies. Maecenas dictum augue eu nulla pellentesque, et varius ante suscipit. Pellentesque sollicitudin quis felis a aliquet. Vestibulum rhoncus mollis finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus diam nisi, consectetur vitae nulla sed, tincidunt porta ante.</p>';
    myclob := myclob || '<p class="lorem">Mauris molestie tellus vel diam venenatis cursus. Sed sit amet lacus vel dolor venenatis pretium. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse eget ex in dui suscipit lobortis. Fusce metus odio, gravida ullamcorper ultricies vel, tempor at diam. Sed eleifend sapien metus, ac volutpat magna dictum vel. Sed aliquet ut arcu viverra vehicula.</p>';
    myclob := myclob || '<p class="lorem">Nam posuere efficitur quam vitae egestas. Ut at nisl mi. Maecenas luctus augue id quam auctor, at commodo quam finibus. Nunc luctus, metus nec dapibus rutrum, orci augue facilisis augue, accumsan finibus nisl augue porttitor nisl. Aenean auctor facilisis tortor, at feugiat leo tempor a. Curabitur nec consequat velit, euismod eleifend libero. Nullam urna ligula, consectetur et molestie nec, venenatis sed orci. Nulla felis odio, imperdiet eget lorem at, lacinia dapibus tortor. Vestibulum nec eros quam. Suspendisse interdum imperdiet libero. Nulla ornare dolor vitae erat pulvinar ornare. Aliquam nulla erat, interdum eu interdum nec, dapibus sed tellus.</p>';
    myclob := myclob || '<p class="lorem">Curabitur laoreet, neque at tempor fringilla, magna tortor dignissim felis, a tincidunt nibh est nec tortor. Sed quis consectetur ante, quis facilisis odio. Phasellus pellentesque sapien elit, quis congue dolor finibus pellentesque. Phasellus efficitur euismod nibh, nec vestibulum ante luctus fermentum. Integer imperdiet ornare nisi pulvinar mattis. Praesent sagittis sit amet enim ut ultrices. Praesent et molestie est. Cras mattis, dui vel mollis euismod, arcu nisi ornare augue, eu malesuada est risus a neque. Proin in posuere ante.</p>';
    myclob := myclob || '<p class="lorem">Nam in iaculis lorem, ut vehicula leo. In hac habitasse platea dictumst. Nam posuere nunc augue, nec tincidunt dui fermentum nec. Fusce augue leo, molestie vel cursus non, tempor faucibus velit. Nunc quis nisl vel orci cursus euismod eu sed diam. Nam consequat eget lectus ac faucibus. In porta lobortis tortor, et suscipit est pretium nec. Aliquam vestibulum tellus a mattis malesuada. Vivamus tortor sem, tincidunt dictum erat sed, sagittis rhoncus nunc. Curabitur nisi elit, tempor eget maximus eu, maximus a ipsum. Proin quis efficitur lorem. Quisque lobortis lacus ac nunc dapibus, a gravida urna dapibus. Morbi eu quam pharetra lorem bibendum dapibus eu eu nisi.</p>';
    myclob := myclob || '<p class="lorem">Duis a ultricies turpis. Nam vitae neque risus. Pellentesque orci velit, pharetra sit amet ullamcorper ac, consequat at metus. Integer mattis ex et gravida mattis. Mauris enim neque, condimentum ac volutpat ac, vehicula et quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut mattis metus. Praesent neque lorem, feugiat quis velit in, tincidunt gravida velit. Donec commodo eros et euismod porta. Maecenas dictum blandit quam ac suscipit. Aenean rhoncus euismod porta. Aliquam vulputate mauris ac ullamcorper vulputate.</p>';
    myclob := myclob || '<p class="lorem">Aliquam magna orci, dignissim sit amet tortor eu, congue facilisis mauris. Maecenas maximus ornare molestie. Praesent vitae eros augue. Sed ullamcorper metus vitae quam gravida, ut dapibus neque sollicitudin. Nulla vel condimentum ex, vitae tristique ex. Suspendisse nec ligula porttitor, rutrum felis in, facilisis mi. Morbi suscipit nunc mauris, non vehicula felis euismod vitae. In eget purus elementum, vehicula odio ut, efficitur nisi. Nullam arcu odio, sollicitudin id orci nec, volutpat luctus mauris. Aenean enim ex, mattis posuere tortor ut, ultrices lacinia nulla.</p>';
    myclob := myclob || '<p class="lorem">Ut aliquam dui enim, eget blandit orci laoreet ut. Phasellus eu sem tincidunt felis malesuada mollis et et est. Nunc auctor placerat augue quis interdum. Praesent semper sodales leo. Donec varius odio fringilla vehicula lobortis. Ut iaculis diam sed diam cursus commodo. Mauris id metus vestibulum, dictum nulla non, mattis eros. Suspendisse sagittis rhoncus odio vitae placerat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pulvinar dui non efficitur consequat. Aliquam congue et quam sed facilisis. Aenean commodo lorem felis, non posuere leo aliquet at.</p>';
    myclob := myclob || '<p class="lorem">In ex mauris, imperdiet fermentum erat quis, consequat fermentum lorem. Etiam rutrum mattis ex nec malesuada. Morbi ac pulvinar ligula. Aliquam quis convallis erat, quis maximus arcu. Aenean tristique purus ut tempus porttitor. Vivamus pharetra tellus ex, sit amet volutpat nunc vulputate eget. Proin suscipit risus luctus elit convallis, a condimentum dolor blandit. Praesent quis egestas ex, sed ultrices sem. In sit amet dolor lorem. Fusce posuere purus ac lacus iaculis, eu rutrum augue commodo. Suspendisse ornare ac nisi vitae maximus. Phasellus felis nibh, congue nec viverra id, ultricies et nisi.</p>';
    myclob := myclob || '<p class="lorem">Pellentesque eget ex et turpis sollicitudin tincidunt. Duis non purus sit amet mi pellentesque fermentum vitae quis ipsum. Nam sollicitudin tempus est, eget finibus libero vulputate non. Duis lacus felis, convallis et tempus a, molestie a felis. Mauris tristique ipsum vel turpis vulputate tempus. Ut ultrices lacus nec libero mollis suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>';
    myclob := myclob || '<p class="lorem">Maecenas non velit at lorem ornare dapibus. Nunc ornare felis vestibulum malesuada sagittis. Pellentesque id libero non lorem tristique iaculis. Vestibulum ullamcorper cursus mauris at molestie. Sed pulvinar orci sit amet dui tempus cursus. Etiam vitae leo ullamcorper, porttitor nulla et, rutrum turpis. Ut venenatis metus at dolor finibus pellentesque. Donec dignissim eros ac mi ornare, vel consequat felis finibus. Ut eu tincidunt nulla. Donec ac condimentum mi. Integer aliquet suscipit velit, eget iaculis felis maximus nec.</p>';
    myclob := myclob || '<p class="lorem">Nunc consectetur sapien sem, et congue risus venenatis vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras at metus placerat, blandit sem fringilla, malesuada felis. Ut non tortor nec augue sodales lobortis. Ut dapibus purus at porttitor dignissim. Vestibulum libero sem, condimentum id metus id, pretium feugiat tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>';
    myclob := myclob || '<p class="lorem">Phasellus auctor erat egestas lectus varius, id faucibus nulla imperdiet. Cras feugiat tristique mattis. Nulla nisi lectus, venenatis non mi non, ultrices maximus tortor. Aliquam vel tellus eu leo aliquet commodo. Morbi a sem luctus, maximus lectus in, iaculis libero. Etiam ac justo elit. Aliquam faucibus sit amet lectus mattis blandit. Pellentesque sit amet felis erat.</p>';
    myclob := myclob || '<p class="lorem">Etiam porttitor faucibus sagittis. Aliquam tempus augue at auctor placerat. Nullam id leo eu arcu lacinia dictum. Suspendisse potenti. Ut quis feugiat leo. Donec lorem orci, accumsan et aliquet ut, sodales ac justo. Pellentesque eleifend erat vel egestas sodales. In a enim eu ipsum varius pulvinar non sed neque. In hac habitasse platea dictumst. Fusce finibus elit nec erat pellentesque, sed condimentum urna accumsan. Sed scelerisque velit a velit blandit, eget euismod dui posuere. Vivamus imperdiet, turpis sed dignissim auctor, quam nisi mollis enim, sit amet fringilla arcu sapien sed felis.</p>';
    myclob := myclob || '<p class="lorem">Vivamus pretium nibh odio, id consectetur ipsum mollis non. Nam sagittis risus id venenatis scelerisque. Vivamus rutrum lorem ac lacinia hendrerit. Fusce iaculis semper nisi, et eleifend metus cursus non. Pellentesque ac varius odio. Nullam dictum, nulla sit amet ultricies pretium, arcu orci tempus sem, eget consequat diam ante quis nisl. Praesent in sem vitae odio sagittis consequat et eget massa. Morbi ut erat in nunc lobortis interdum scelerisque eu arcu. Ut bibendum quam ipsum, vel aliquam arcu facilisis vulputate. Mauris vitae nibh eget dui maximus ultrices.</p>';
    myclob := myclob || '<p class="lorem">Donec quis turpis est. Donec aliquam lacus vitae dui auctor vestibulum. Fusce malesuada laoreet metus, in pharetra est rutrum id. Cras auctor dignissim ullamcorper. Donec tempus maximus ante, a egestas ante aliquet in. Maecenas ut sem sit amet dolor lacinia sodales. Sed consectetur libero vel bibendum convallis. Suspendisse ultrices urna tellus. Sed in nulla iaculis, pulvinar purus at, commodo magna. Maecenas sed metus eu lacus feugiat molestie. Phasellus ut viverra justo, a fringilla elit. Cras pellentesque lacus augue, et molestie arcu ornare eu.</p>';
    myclob := myclob || '<p class="lorem">Aliquam urna velit, pulvinar et luctus facilisis, congue et massa. Suspendisse urna velit, pretium non imperdiet vel, hendrerit semper ligula. Suspendisse dictum tristique nunc in cursus. Nam tristique leo nec nisl tincidunt dictum. Morbi ullamcorper finibus ipsum. In sodales nunc a sollicitudin efficitur. Sed eget augue felis. Proin elit ligula, viverra nec ligula ac, convallis mollis libero. Curabitur laoreet pulvinar eros, id tristique neque maximus et. Suspendisse a blandit sem, vitae porttitor ligula. Pellentesque viverra vitae massa sed dignissim. Mauris at erat magna. Mauris suscipit mauris augue, vel pulvinar augue sollicitudin et. Nulla pulvinar pellentesque elit, nec facilisis ligula pharetra sit amet. Sed nec ligula mattis, interdum lacus at, vehicula sem. Cras commodo nunc vel ligula tempor, porttitor laoreet massa ultrices.</p>';
    myclob := myclob || '<p class="lorem">Donec porttitor vitae eros non volutpat. Cras odio est, congue at pulvinar vel, pulvinar id dui. Duis commodo massa risus, eget dignissim velit iaculis eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce dolor lacus, pharetra sit amet porta quis, euismod vel diam. Quisque placerat dignissim arcu, eget imperdiet dolor rhoncus non. Suspendisse quis mollis purus, cursus euismod neque. Aliquam in iaculis velit, sed elementum nulla. Vestibulum accumsan scelerisque posuere. Morbi a dictum nisi. Fusce tristique mauris arcu, at volutpat ipsum tempor vestibulum. Nunc et fermentum metus. Maecenas pretium tempor odio, sit amet pretium felis maximus at.</p>';
    myclob := myclob || '<p class="lorem">Suspendisse euismod arcu ut enim bibendum dignissim. Donec porta justo dolor. In ac velit in odio volutpat ornare. Cras auctor felis sed egestas ultricies. Nullam odio diam, pretium a nulla ut, lacinia posuere lorem. Sed sed ligula et eros interdum faucibus eget eget diam. Etiam sodales posuere arcu placerat ultricies. Maecenas placerat viverra est. Praesent purus sapien, efficitur ut cursus non, sagittis sit amet ex. Quisque non mauris sed purus sodales convallis sed lobortis dui. Pellentesque velit risus, cursus in erat id, rutrum fermentum mauris. Suspendisse libero nunc, luctus in consectetur non, accumsan sodales mi. Nulla mi turpis, fringilla at mauris ut, tempor vestibulum metus. Duis consectetur fermentum mi.</p>';
    myclob := myclob || '<p class="lorem">Duis risus erat, maximus ut dapibus sit amet, tristique eu sapien. Etiam volutpat, mauris facilisis elementum ullamcorper, est mi ornare ex, sed auctor enim eros id nunc. Praesent molestie, erat eget auctor egestas, lacus sapien scelerisque nisl, et aliquet ligula elit id risus. Donec fringilla placerat lectus in laoreet. Aenean finibus, elit eu ultrices tempor, magna est faucibus libero, porttitor placerat turpis nibh a risus. In ac rhoncus sem. Vivamus at tellus neque. Aliquam vulputate molestie turpis ut feugiat. Nulla hendrerit est id tortor aliquam finibus. Mauris imperdiet velit et lorem gravida, vel vulputate diam hendrerit. Ut accumsan efficitur pellentesque.</p>';
    myclob := myclob || '<p class="lorem">In consequat mi nec bibendum ultricies. Etiam eu sapien feugiat, venenatis est in, rutrum felis. Cras eu ante finibus, tempor nunc eu, aliquam dolor. Nulla finibus sapien maximus mauris vehicula, quis aliquet erat finibus. Suspendisse potenti. Quisque quis semper mauris. Vivamus hendrerit molestie justo ac porta. Nunc semper congue accumsan.</p>';
    myclob := myclob || '<p class="lorem">Maecenas luctus magna ac semper vehicula. Integer interdum eleifend ex, vel rhoncus libero efficitur et. Donec ultrices viverra lacus ac eleifend. Fusce ornare in sem egestas fringilla. Duis commodo turpis a sem pulvinar condimentum. Morbi a mauris vitae enim fermentum sagittis sit amet non ante. Nullam tincidunt nisl in tortor pulvinar rhoncus. Integer sed leo vel mauris ornare laoreet. Donec quis porttitor augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dictum commodo orci, at facilisis ligula dictum a. Pellentesque velit enim, rutrum id turpis in, maximus aliquam leo. Vestibulum blandit porta orci sed volutpat. Suspendisse facilisis ipsum tempor, lacinia ante non, congue tortor. Nunc ullamcorper lacus ut nisi ultrices malesuada.</p>';
    myclob := myclob || '<p class="lorem">Aliquam suscipit hendrerit ligula blandit venenatis. Sed et eros in nibh gravida congue ac vitae leo. Integer id leo in urna laoreet rhoncus. Donec eget blandit nunc. Praesent lobortis quam tellus, et ornare ligula vulputate id. Aliquam pellentesque orci blandit suscipit lacinia. Fusce interdum auctor dui, commodo consectetur leo. Aliquam facilisis, risus in venenatis facilisis, nulla felis consectetur sapien, nec eleifend leo tellus ac magna. Fusce feugiat est leo, id mollis ex ultricies in. Proin vulputate, sapien vitae semper dictum, libero mauris pharetra purus, id imperdiet purus eros et neque. Nulla pretium accumsan nulla, in placerat tellus egestas non. Nam odio orci, consequat vel odio ut, ullamcorper ultrices velit. Nunc ornare magna et orci blandit convallis.</p>';
    
    apex_collection.create_collection( 'TEST_CLOB' );
    apex_collection.add_member( 'TEST_CLOB', p_clob001 => myclob );
END;